Private event features
AdfPizarro/private-event pull request #2
Opened 2020-09-23 20:42 UTC by AdfPizarro

You can sign in and login
-Create events
-View all the events
-See the past and upcoming events
-Attend to events
-See your appointments

2020-09-23 22:53 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @AdfPizarro, you did a great job on this project :+1: Awesome!!! However, there a few comments we need to address to get our project approved :100: Kindly check the comments below:
- `Events show` page should display the list of attendants. There is currently no button for users to click to indicate whether they are attending or not. Let us add a button action for that :slightly_smiling_face: 
- `Users show` page should display events the user has created and events that the user is attending to separated in `past` and `upcoming`. Currently, this is what we have. Check image below
![sh](https://user-images.githubusercontent.com/46388113/94076310-4b8f1980-fdec-11ea-9dcf-4ffcde42d7bc.png)
- We are currently missing a test for our project. Let us implement test
![tsss](https://user-images.githubusercontent.com/46388113/94081689-aaee2900-fdee-11ea-85c5-f44c880485f3.png)
- Kindly remove all commented code, code commented should be removed

[Optional]
- Kindly the association of the `attendee` model, it can be improved

Once this is resolved, kindly submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-09-23 22:53 UTC, addod19 commented on app/models/user.rb
> +  has_many :events, foreign_key: :creator
Kindly replace the `:creator` with `:creator_id`

2020-09-23 22:53 UTC, addod19 commented on app/controllers/users_controller.rb
> +    @events = current_user.appointments
`UserController` show; 
- list events created by user, ie. `@created_events = user.events`
- list events previously attended by user, using event scope `@past_events = user.attended_events.previous`
- list upcoming event previously attended by user, using event scope `@past_events = user.attended_events.previous`

2020-10-01 17:33 UTC, AdfPizarro commented on app/controllers/users_controller.rb
> +    @events = current_user.appointments
Added the display in the user show page

2020-10-01 17:44 UTC, AdfPizarro commented on app/models/user.rb
> +  has_many :events, foreign_key: :creator
Renamed and removed the commented line

2020-10-03 06:18 UTC, sumancrest0001 approved these changes
**Status: Approved:100: 
Congratulations @AdfPizarro :clap: :clap: **
Thank you for making all the changes requested by the previous TSE. It is approved. Now you can move to the next project.
Happy coding !!!

2020-10-05 14:11 UTC, merged